### PR TITLE
Add https://thejavaguy.org/

### PR DESCRIPTION
**Pull request by TheJavaGuy**
Hi Den,

I'm adding my blog to the Technology section. I write about Java and related technologies. No ads, no tracking, no Google Analytics, no pop-ups.

### CODE REVIEW

**Comment by dend** [comment]
@TheJavaGuy - can you please include the name instead of `TheJavaGuy`?

**Comment by TheJavaGuy** [comment]
@dend You mean my name, like this `[blogs.ivanmilosavljevic]`?

**Comment by dend** [comment]
@TheJavaGuy no, the identifier should be a "normalized" version of the domain. Just the `title`.

**Comment by TheJavaGuy** [comment]
@dend Thank you, all clear, done ✅

**Pull request merged**
