### PR TITLE
add Jayden Garridan Bridges

### PR DESCRIPTION
**Pull request by jackeyjack1**

### CODE REVIEW

**Comment by dend** [comment]
@jackeyjack1 unclear what the site is - is this a personal digital garden? Blog?

**Comment by jackeyjack1** [comment]
Hello! I can't believe I didn't write a comment in my initial commit, how rude of me, apologies! I was submitting my site as a blog, but seems I linked to my homepage / garden section instead. I have corrected this and now link straight to my blog. Additionally, I have resolved the merge conflict, all the best, let me know if anything! 🙏

**Comment by jackeyjack1** [comment]
@dend Don't leave us hanging again, yo! This really is a cool project, but I understand life can get busy. Wishing nothing but the best 🙏

**Comment by jackeyjack1** [comment]
Resolved again.. Guess I'm not welcome though? Oh well.

**Comment by jackeyjack1** [comment]
https://youtu.be/6dYWe1c3OyU

**Pull request closed without merging**
